info:
  contact: {}
  description: bsf 示例文档
  license: {}
  termsOfService: http://swagger.io/terms/
  title: Example API 文档
  version: "1.0"
paths:
  /Auth/Hello:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 测试
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试
      tags:
      - Test
swagger: "2.0"
